;;/*
;;* Copyright (c) 2022 Renesas Electronics Corporation and/or its affiliates
;;*
;;* SPDX-License-Identifier: BSD-3-Clause
;;*/
;;/***********************************************************************************************************************
;;* File Name    : r_bsp_config_reference.inc
;;* H/W Platform : GENERIC_RL78_G15
;;* Description  : 
;;***********************************************************************************************************************/
;;/***********************************************************************************************************************
;;* History : DD.MM.YYYY Version  Description
;;*         : 31.05.2022 1.30     First Release
;;*         : 04.07.2025 1.92     Changed the disclaimer.
;;***********************************************************************************************************************/

#ifdef __r_bsp_config_inc__
#else

#define __r_bsp_config_inc__                   (1)
#define BSP_CFG_ASM_RTOS_USED                  (0)

#endif
