/***********************************************************************************************************************
 * DISCLAIMER
 * This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
 * No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
 * applicable laws, including copyright laws.
 * THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
 * OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
 * LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
 * INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
 * ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
 * Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability
 * of this software. By using this software, you agree to the additional terms and conditions found by accessing the
 * following link:
 * http://www.renesas.com/disclaimer
 *
 * Copyright (C) 2020 Renesas Electronics Corporation. All rights reserved.
 ***********************************************************************************************************************/

/***********************************************************************************************************************
 *  File Name    : LRC_FPB_RL78G15.c
 *  Description  : Main Program
 *  Creation Date: 2026-04-29
 *  This file was generated by Smart Configurator.
 ***********************************************************************************************************************/
#include "LRC_Core.h"
#include "r_rfsp_common_api.h"
#include "r_smc_entry.h"
#include "sample_control_data_flash.h"
#include <string.h>
#include "csvbin.h"

#define L_MCLK_FREQ_1MHz (1000000uL)
#define L_MCLK_ROUNDUP_VALUE (999999uL)

#define DATAFLASH_BASE_ADDRESS (0x9000u)

static LRC_Config lrc_cfg = {
    .ac_trip =
        {
            .persistence = 1,
            .threshold = LRC_FLOAT_TO_FXP(0.029f),
        },
    .dc_trip =
        {
            .persistence = 1,
            .threshold = LRC_FLOAT_TO_FXP(0.029f),
        },
};

LRC_Channel lrc_channel;

uint8_t g_rx_buf[2U] = {0U, 0U};
bool transmit_meta = false;
uint8_t uart_buffer[32] = {0,};
csvbin_t csvbuf;
bool adc_ready = false;
bool sw_pressed = false;

/** @brief Initialises dataflash for writing & reading later*/
static void Dataflash_init(void);

/** @brief Writes coefficient to the dataflash
 * @param[in] coeff - coefficient to write
 */
static void Dataflash_write_coeff(const fxp_t coeff);

/** @brief Reads coefficient from the dataflash, if one isn't present, returns default value.
 * @return coefficient from dataflash (or default value if one isn't present
 */
static fxp_t Dataflash_read_coeff(void);

/** @brief Perform channel coefficient computation*/
static void Coeff_compute(void);

void main(void)
{
  EI();

  /* Setup csvbin*/
  /* Initialise the csvbin streamer*/
  Csvbin_init(&csvbuf, uart_buffer, 32);
  /* Set the metadata*/
  Csvbin_set_meta(&csvbuf, "#NADC,RMS\n", "#Ti32,q17.15\n", "#Elittle\n");
  R_Config_UART0_Start();
  R_Config_UART0_Receive(g_rx_buf, 1U);

  /* Setup LRC*/
  LRC_Init(&lrc_cfg);
  LRC_ChannelRegister(&lrc_channel);

  /* Enable switch based calib trigger*/
  R_Config_INTC_INTP0_Start();

  /* Prepare*/
  Dataflash_init();

  /* Get coefficient data*/
  LRC_ChannelCoeffSet(&lrc_channel, Dataflash_read_coeff());

  LRC_Start();

  while (1)
  {
      /* Transmit meta on request*/
      if(transmit_meta)
      {
          Csvbin_transmit_meta(&csvbuf);
          transmit_meta = false;
      }

      /* If switched has been pressed - compute new calibration and store it*/
      if(sw_pressed)
      {
    	  Coeff_compute();
    	  sw_pressed = false;
      }

      /* Transmit new data if ADC reading completed*/
      if(adc_ready)
      {
    	  static volatile spl_t adc = 0;
    	  static volatile fxp_t rms = 0;

    	  adc = lrc_channel.inputs.i_sample;
    	  rms = lrc_channel.ac_data.output;
    	  adc_ready = false;

    	  if(adc < -10000L)
    	  {
    		  NOP();
    		  NOP();
    		  NOP();
    		  NOP();
    		  NOP();
    		  NOP();
    		  NOP();
    	  }

    	  /* Add data fields*/
    	  Csvbin_add_field(&csvbuf, (uint8_t*)&adc, sizeof(spl_t));
          Csvbin_add_field(&csvbuf, (uint8_t*)&rms, sizeof(fxp_t));

          /* Terminate & Transmit*/
          Csvbin_end_row(&csvbuf);
          Csvbin_transmit(&csvbuf);
      }
  }
}

static void Dataflash_init(void)
{
  uint16_t wait_count;
  uint32_t l_mclk_freq;

  l_mclk_freq = R_BSP_GetFclkFreqHz();
  l_mclk_freq = (l_mclk_freq + L_MCLK_ROUNDUP_VALUE) / L_MCLK_FREQ_1MHz;

  /* Oscillation stable time for HOCO. */
  for (wait_count = ((30 * (uint16_t)l_mclk_freq) / 4); wait_count > 0; wait_count--)
  {
    BSP_NOP();
  }

  if (R_RFSP_ENUM_RET_STS_OK != R_RFSP_Init((uint8_t)l_mclk_freq))
  {
    /* TODO: Handle Error*/
  }
}

static void Dataflash_write_coeff(const fxp_t coeff)
{
  static __near uint8_t df_buf[] = {0xA5, 0xA5, 0xA5, 0xA5, 0x00, 0x00, 0x00, 0x00};

  /* Place fxp_t in buffer*/
  (void)memcpy(&df_buf[4], &coeff, sizeof(fxp_t));

  /* Then write the buffer*/
  if (SAMPLE_ENUM_RET_STS_OK != Sample_DataFlashControl(DATAFLASH_BASE_ADDRESS, sizeof(df_buf), df_buf))
  {
    /* TODO: Handle Error*/
  }
}

static fxp_t Dataflash_read_coeff(void)
{
  volatile fxp_t ret_value = 0L;

  if(0xA5A5A5A5 == (*(uint32_t *)DATAFLASH_BASE_ADDRESS))
  {
	  ret_value = *(uint32_t *)(DATAFLASH_BASE_ADDRESS + 4);
  }
  else
  {
	  ret_value = (fxp_t)0x1F61A904;
  }

  return ret_value;
}

static void Coeff_compute(void)
{
  fxp_t l_coeff = LRC_ChannelCoeffCompute(&lrc_channel, 0.03f);

  Dataflash_write_coeff(l_coeff);

  LRC_Stop();
  LRC_ChannelCoeffSet(&lrc_channel, l_coeff);
  LRC_Start();
}
