/***********************************************************************************************************************
 * DISCLAIMER
 * This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
 * No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
 * applicable laws, including copyright laws.
 * THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
 * OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
 * LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
 * INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
 * ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
 * Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability
 * of this software. By using this software, you agree to the additional terms and conditions found by accessing the
 * following link:
 * http://www.renesas.com/disclaimer
 *
 * Copyright (C) 2020 Renesas Electronics Corporation. All rights reserved.
 ***********************************************************************************************************************/

/***********************************************************************************************************************
 *  File Name    : LRC_FPB_RL78G15.c
 *  Description  : Main Program
 *  Creation Date: 2026-04-29
 *  This file was generated by Smart Configurator.
 ***********************************************************************************************************************/
#include "LRC_Core.h"
#include "Menu.h"
#include "r_rfsp_common_api.h"
#include "r_smc_entry.h"
#include "sample_control_data_flash.h"
#include <string.h>

#define L_MCLK_FREQ_1MHz (1000000uL)
#define L_MCLK_ROUNDUP_VALUE (999999uL)

#define DATAFLASH_BASE_ADDRESS (0x9000u)

static LRC_Config lrc_cfg = {
    .ac_trip =
        {
            .persistence = 1,
            .threshold = LRC_FLOAT_TO_FXP(0.029f),
        },
    .dc_trip =
        {
            .persistence = 1,
            .threshold = LRC_FLOAT_TO_FXP(0.029f),
        },
};

LRC_Channel lrc_channel;

/** @brief Initialises dataflash for writing & reading later*/
static void Dataflash_init(void);

/** @brief Writes coefficient to the dataflash
 * @param[in] coeff - coefficient to write
 */
static void Dataflash_write_coeff(const fxp_t coeff);

/** @brief Reads coefficient from the dataflash, if one isn't present, returns default value.
 * @return coefficient from dataflash (or default value if one isn't present
 */
static fxp_t Dataflash_read_coeff(void);

/**
 * @brief itoa function implementation to print numbers in hex format
 * @param value - number to print (singed 32bit)
 * @return - pointer to finished conversion (hex string)
 */
static char *itoa_hex_int32(int32_t value);

/** @brief Perform channel coefficient computation*/
static void Coeff_compute(char *p_args);

/** @brief Prints the rms in fixed point (hex)*/
static void Rms_print(char *p_args);

/** @brief Resets MCU via illegal memory access call*/
static void Reset(char *p_args);

/* Menuing*/
Menu main_menu = {.p_name = "Main Menu"};

Menu_option coeff_option = {
    .p_cmd = "coeff",
    .p_help = "Computes channel coefficient (similar to calibration) with assumed reference current of 30ma (0.03A)\r\n",
    .option_type = ACTION,
    .option.action = &Coeff_compute};

Menu_option rms_option = {
    .p_cmd = "rms", .p_help = "Prints the rms in fixed point (hex)", .option_type = ACTION, .option.action = &Rms_print};

Menu_option reset_option = {
    .p_cmd = "reset", .p_help = "Resets MCU via illegal memory access call", .option_type = ACTION, .option.action = &Reset};

void main(void)
{
  EI();

  /* Setup menu*/
  Menu_init(&main_menu);
  Menu_register_option(&main_menu, &coeff_option);
  Menu_register_option(&main_menu, &rms_option);
  Menu_register_option(&main_menu, &reset_option);

  /* Clear Screen & Home cursor*/
  Menu_print("\033[2J");
  Menu_print("\033[H");
  Menu_print("Initialising LRC...");

  /* Setup LRC*/
  LRC_Init(&lrc_cfg);
  LRC_ChannelRegister(&lrc_channel);

  /* Prepare*/
  Dataflash_init();

  /* Get coefficient data*/
  LRC_ChannelCoeffSet(&lrc_channel, Dataflash_read_coeff());

  Menu_print("Done!\r\n");

  Menu_print("Starting LRC...");

  LRC_Start();

  Menu_print("Done!\r\n");

  Menu_print_help();

  while (1)
  {
    Menu_handler();
  }
}

static void Dataflash_init(void)
{
  uint16_t wait_count;
  uint32_t l_mclk_freq;

  l_mclk_freq = R_BSP_GetFclkFreqHz();
  l_mclk_freq = (l_mclk_freq + L_MCLK_ROUNDUP_VALUE) / L_MCLK_FREQ_1MHz;

  /* Oscillation stable time for HOCO. */
  for (wait_count = ((30 * (uint16_t)l_mclk_freq) / 4); wait_count > 0; wait_count--)
  {
    BSP_NOP();
  }

  if (R_RFSP_ENUM_RET_STS_OK != R_RFSP_Init((uint8_t)l_mclk_freq))
  {
    /* TODO: Handle Error*/
  }
}

static void Dataflash_write_coeff(const fxp_t coeff)
{
  static __near uint8_t df_buf[] = {0xA5, 0xA5, 0xA5, 0xA5, 0x00, 0x00, 0x00, 0x00};

  /* Place fxp_t in buffer*/
  (void)memcpy(&df_buf[4], &coeff, sizeof(fxp_t));

  /* Then write the buffer*/
  if (SAMPLE_ENUM_RET_STS_OK != Sample_DataFlashControl(DATAFLASH_BASE_ADDRESS, sizeof(df_buf), df_buf))
  {
    /* TODO: Handle Error*/
  }
}

static fxp_t Dataflash_read_coeff(void)
{
  fxp_t ret_value = 0x1F61A904;

  /* If the magic key is there, we can be confident enough for a sample application that the coefficient is*/
  if (0xA5 == (*(uint8_t *)DATAFLASH_BASE_ADDRESS) && 0xA5 == (*(uint8_t *)DATAFLASH_BASE_ADDRESS + 1) &&
      0xA5 == (*(uint8_t *)DATAFLASH_BASE_ADDRESS + 2) && 0xA5 == (*(uint8_t *)DATAFLASH_BASE_ADDRESS + 3))
  {
    (void)memcpy((uint8_t *)&ret_value, (uint8_t *)(DATAFLASH_BASE_ADDRESS + 4), sizeof(fxp_t));
    Menu_print("\t\tCoefficient Found in VEEPROM!\r\n");
  }
  else
  {
    Menu_print("\t\tCoefficient NOT Found in VEEPROM - using default!\r\n");
  }

  Menu_print("\t\tCoefficient: ");
  Menu_print(itoa_hex_int32((int32_t)ret_value));

  return ret_value;
}

static char *itoa_hex_int32(int32_t value)
{
  static const char hex_digits[] = "0123456789ABCDEF";
  static char text_buffer[] = {0};

  char *p = text_buffer;
  char *start;

  text_buffer[0] = 0;
  text_buffer[1] = 0;
  text_buffer[2] = 0;
  text_buffer[3] = 0;
  text_buffer[4] = 0;
  text_buffer[5] = 0;
  text_buffer[6] = 0;
  text_buffer[7] = 0;

  /* Special case: value == 0 */
  if (value == 0)
  {
    *p++ = '0';
    *p = '\0';
    return text_buffer;
  }

  start = p;

  /* Convert nibble by nibble (LSB first) */
  while (value != 0)
  {
    *p++ = hex_digits[value & 0xF];
    value >>= 4;
  }

  *p = '\0';

  /* Reverse the string */
  for (--p; start < p; ++start, --p)
  {
    char tmp = *start;
    *start = *p;
    *p = tmp;
  }

  return text_buffer;
}

static void Coeff_compute(char *p_args)
{
  fxp_t l_coeff = LRC_ChannelCoeffCompute(&lrc_channel, 0.03f);

  Menu_print("\r\nAssumed reference signal current: 30mA");
  Menu_print("\r\nCoefficient computed: ");
  Menu_print(itoa_hex_int32((int32_t)l_coeff));
  Menu_print("\r\n\r\n");

  Menu_print("\r\nStoring coefficient in Dataflash...");
  Dataflash_write_coeff(l_coeff);
  Menu_print("Done!");

  Menu_print("\r\nStopping LRC, updating coefficient & restarting...");
  LRC_Stop();
  LRC_ChannelCoeffSet(&lrc_channel, l_coeff);
  LRC_Start();
  Menu_print("Done!");
}

static void Rms_print(char *p_args)
{
  (void)p_args;

  Menu_print("\r\nRMS (fixed point): ");
  Menu_print(itoa_hex_int32((int32_t)lrc_channel.ac_data.output));
  Menu_print(" [A]");

  Menu_print("\r\nDC (fixed point): ");
  Menu_print(itoa_hex_int32((int32_t)lrc_channel.dc_data.output));
  Menu_print(" [A]");

  Menu_print("\r\nTo convert to float divide these numbers by: ");
  Menu_print(itoa_hex_int32((int32_t)(1 << FXP_FRAC_BITS)));
}

static void Reset(char *p_args)
{
  (void)p_args;

  __far uint16_t *ptr;

  ptr = (__far uint16_t *)0x00011800;

  /* Illegal address access */
  *ptr = 0xFFFF;
}
